const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const K={job:'cnc828.job.v1',ops:'cnc828.ops.v1',theme:'cnc828.theme.v1',turret:'cnc828.turret.v2',measure:'cnc828.measure.v2',checks:'cnc828.checks.v2'};
const MACHINE={name:'Tengyue CK52PT-Y',control:'Siemens 828D · ShopTurn',maxRpm:4000,bar:52,turret:15};
const SETUP=[['clamp','Зажим детали и кулачки проверены'],['zero','Ноль детали / G54 проверен'],['tools','Инструмент и корректоры проверены'],['clearance','Вылеты и безопасные расстояния проверены'],['firstRun','Первый проход — сниженная скорость / Single Block']];
const S={job:null,ops:[],turret:Array(15).fill(null),measurements:[],checks:{}};let editingOp=-1,editingSlot=-1;
const diag={squeal:['Уменьши обороты на 10–15% и проверь, меняется ли тон.','Проверь вылет и жёсткость державки.','Не занижай подачу до трения: пластина должна резать.','Проверь износ и геометрию пластины.','Для нержавейки обеспечь стабильную СОЖ.'],vibration:['Проверь вылет инструмента и детали.','Снизь обороты на 15–25% и повтори проход.','Проверь крепление державки, пластины и заготовки.','Измени глубину резания, если работа идёт на границе радиуса вершины.'],chips:['Сверь подачу с диапазоном стружколома.','Если стружка длинная и всё стабильно — повышай подачу небольшими шагами.','Проверь глубину резания и направление СОЖ.'],size:['Проверь повторяемость измерения и температуру детали.','Проверь износ кромки и налипание.','Зафиксируй тренд по нескольким деталям перед коррекцией.','На чистовой держи постоянный припуск.']};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safe=(key,fallback)=>{try{const v=JSON.parse(localStorage.getItem(key));return v??fallback}catch{return fallback}};
function load(){S.job=safe(K.job,null);S.ops=safe(K.ops,[]);S.turret=safe(K.turret,Array(15).fill(null));S.measurements=safe(K.measure,[]);S.checks=safe(K.checks,{});if(!Array.isArray(S.turret))S.turret=[];S.turret=[...S.turret.slice(0,15),...Array(Math.max(0,15-S.turret.length)).fill(null)];if(localStorage.getItem(K.theme)==='light')document.documentElement.classList.add('light')}
function save(){S.job?localStorage.setItem(K.job,JSON.stringify(S.job)):localStorage.removeItem(K.job);localStorage.setItem(K.ops,JSON.stringify(S.ops));localStorage.setItem(K.turret,JSON.stringify(S.turret));localStorage.setItem(K.measure,JSON.stringify(S.measurements));localStorage.setItem(K.checks,JSON.stringify(S.checks))}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1900)}
function injectUI(){
  if(!$('#v02css')){const l=document.createElement('link');l.id='v02css';l.rel='stylesheet';l.href='./src/v02.css';document.head.append(l)}
  const version=$('.hero .eyebrow');if(version)version.textContent='CNC ASSISTANT · v0.3';
  const actions=$('#jobForm .form-actions');if(actions&&!$('#exportProjectBtn'))actions.insertAdjacentHTML('beforeend','<button class="btn ghost" type="button" id="exportProjectBtn">Экспорт проекта</button><button class="btn ghost" type="button" id="importProjectBtn">Импорт</button><span class="backup-note">JSON · полностью локально</span><input id="importProjectFile" type="file" accept="application/json,.json" hidden>');
  const split=$('#view-job .content-split');if(split&&!$('#jobToolsGrid'))split.insertAdjacentHTML('afterend',`<div class="job-tools-grid" id="jobToolsGrid"><section class="panel work-panel"><div class="panel-title"><div><span class="eyebrow">ПЕРЕД ЗАПУСКОМ</span><h3>Setup checklist</h3><small>Состояние сохраняется вместе с деталью</small></div><span class="local-chip" id="setupCount">0 / ${SETUP.length}</span></div><div class="setup-list" id="setupList"></div><div class="setup-meter"><div class="setup-meter-top"><span>Готовность установки</span><b id="setupPct">0%</b></div><div class="setup-meter-track"><span id="setupBar"></span></div></div></section><section class="panel work-panel"><div class="panel-title"><div><span class="eyebrow">КОНТРОЛЬ</span><h3>Журнал размеров</h3><small>Быстрый контроль партии и ухода размера</small></div><button class="text-btn" type="button" id="clearMeasuresBtn">Очистить</button></div><form class="measure-form" id="measureForm"><label><span>Размер</span><input id="mName" placeholder="Ø40"></label><label><span>Номинал</span><input id="mTarget" type="number" step="0.001" placeholder="40"></label><label><span>Нижн.</span><input id="mLow" type="number" step="0.001" value="0"></label><label><span>Верхн.</span><input id="mHigh" type="number" step="0.001" value="0.02"></label><label><span>Факт</span><input id="mActual" type="number" step="0.001" placeholder="40.01"></label><button class="btn primary compact" type="submit">Добавить</button></form><div class="measure-table" id="measureTable"></div></section></div>`);
  const process=$('.process-panel');if(process&&!$('#routeSummary')){$('.process-top',process)?.insertAdjacentHTML('afterend','<div class="route-summary" id="routeSummary"></div>')}
  const machine=$('#view-machine');if(machine&&!$('#turretSection'))machine.insertAdjacentHTML('beforeend',`<section class="panel turret-section" id="turretSection"><div class="turret-head"><div><span class="eyebrow">РЕВОЛЬВЕР</span><h2 style="margin:0">15 позиций · BMT40</h2><p style="margin:6px 0 0;color:var(--muted);font-size:12px">Нажми позицию и запиши реальный инструмент. Он появится при создании операций.</p></div><button class="btn ghost compact" id="clearTurretBtn">Очистить револьвер</button></div><div class="turret-grid" id="turretGrid"></div></section>`);
  const calcModal=$('#calculatorModal');if(calcModal&&!$('#calcLimit'))calcModal.insertAdjacentHTML('beforeend','<div class="limit-banner" id="calcLimit"></div>');
  const opTool=$('#opTool');if(opTool){opTool.setAttribute('list','turretTools');if(!$('#turretTools'))opTool.insertAdjacentHTML('afterend','<datalist id="turretTools"></datalist>')}
  if(!$('#toolModal'))document.body.insertAdjacentHTML('beforeend',`<dialog class="modal wide-modal" id="toolModal"><div class="modal-head"><div><span class="eyebrow">РЕВОЛЬВЕР</span><h2 id="toolModalTitle">Позиция T01</h2></div><button class="close-btn" data-close>×</button></div><form id="toolForm" class="tool-form"><label><span>Тип</span><select id="toolType"><option>Наружный резец</option><option>Расточной резец</option><option>Канавочный / отрезной</option><option>Резьбовой</option><option>Сверло</option><option>Приводной инструмент</option><option>Метчик</option><option>Другое</option></select></label><label><span>Обозначение / державка</span><input id="toolName" placeholder="SCLCR / PCLNR / BMT40-ER25"></label><label><span>Пластина / оснастка</span><input id="toolInsert" placeholder="CNMG120404 / Ø20 drill"></label><label><span>Вылет, мм</span><input id="toolStick" type="number" step="0.1" placeholder="35"></label><label class="wide"><span>Комментарий</span><input id="toolNote" placeholder="Черновой, чистовой, СОЖ…"></label><div class="tool-form-actions"><button class="btn primary" type="submit">Сохранить позицию</button><button class="btn danger-ghost" id="removeToolBtn" type="button">Освободить позицию</button></div></form></dialog>`);
}
function initMobileDockBehavior(){
  const dock=$('.mobile-nav');
  const scroller=$('.workspace');
  if(!dock||!scroller)return;

  let lastY=Math.max(0,scroller.scrollTop||0);
  let ticking=false;

  const show=()=>dock.classList.remove('is-hidden');
  const hide=()=>dock.classList.add('is-hidden');

  const update=()=>{
    const y=Math.max(0,scroller.scrollTop||0);
    const delta=y-lastY;

    if(window.innerWidth>720||y<80) show();
    else if(delta>9&&y>130) hide();
    else if(delta<-7) show();

    lastY=y;
    ticking=false;
  };

  scroller.addEventListener('scroll',()=>{
    if(!ticking){
      ticking=true;
      requestAnimationFrame(update);
    }
  },{passive:true});

  window.addEventListener('resize',()=>{
    if(window.innerWidth>720)show();
    lastY=Math.max(0,scroller.scrollTop||0);
  },{passive:true});

  document.addEventListener('touchstart',e=>{
    const y=e.touches?.[0]?.clientY;
    const viewportH=document.documentElement.clientHeight;
    if(window.innerWidth<=720&&Number.isFinite(y)&&y>viewportH-105)show();
  },{passive:true});

  dock.addEventListener('pointerdown',show,{passive:true});
  $$('.mobile-nav button').forEach(button=>button.addEventListener('click',show));
}

initMobileDockBehavior();

function nav(v){$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));if(v==='job'){renderJob();renderSetup();renderMeasurements()}if(v==='technology')renderOps();if(v==='machine')renderTurret();scrollTo({top:0,behavior:'smooth'})}
function renderHome(){const b=$('#jobProgress .progress-track span'),m=$('#jobProgress .progress-meta');if(!S.job){$('#currentJobTitle').textContent='Деталь не выбрана';b.style.width='0%';m.innerHTML='<span>Создай карточку детали</span><b>0%</b>';return}$('#currentJobTitle').textContent=S.job.name||'Без названия';const done=SETUP.filter(([k])=>S.checks[k]).length;const parts=[S.job.name,S.job.material,S.job.stockDiameter,S.job.controlDims,S.ops.length,done===SETUP.length].filter(Boolean).length;const p=Math.min(100,Math.round(parts/6*100));b.style.width=p+'%';m.innerHTML=`<span>${esc(S.job.material)} · Ø${esc(S.job.stockDiameter||'—')} · ${S.ops.length} оп. · setup ${done}/${SETUP.length}</span><b>${p}%</b>`}
function renderJob(){const j=S.job||{};$('#jobName').value=j.name||'';$('#jobMaterial').value=j.material||'AISI 304';$('#stockDiameter').value=j.stockDiameter||'';$('#stockLength').value=j.stockLength||'';$('#jobQty').value=j.qty||1;$('#jobZero').value=j.zero||'G54 · торец детали';$('#controlDims').value=j.controlDims||'';$('#jobNotes').value=j.notes||'';$('#jobContextName').textContent=j.name||'Новая деталь';const d=$$('#jobContextList dd');if(d.length>=4){d[0].textContent=j.material||'—';d[1].textContent=j.stockDiameter?`Ø${j.stockDiameter} × ${j.stockLength||'—'} мм`:'—';d[2].textContent=j.qty?j.qty+' шт.':'—';d[3].textContent=j.zero||'—'}}
function renderSetup(){const root=$('#setupList');if(!root)return;root.innerHTML=SETUP.map(([k,label])=>`<label class="setup-check ${S.checks[k]?'checked':''}"><input type="checkbox" data-check="${k}" ${S.checks[k]?'checked':''}><span>${label}</span></label>`).join('');const done=SETUP.filter(([k])=>S.checks[k]).length,p=Math.round(done/SETUP.length*100);$('#setupCount').textContent=`${done} / ${SETUP.length}`;$('#setupPct').textContent=p+'%';$('#setupBar').style.width=p+'%';$$('[data-check]',root).forEach(i=>i.onchange=()=>{S.checks[i.dataset.check]=i.checked;save();renderSetup();renderHome()})}
function renderMeasurements(){const root=$('#measureTable');if(!root)return;if(!S.measurements.length){root.innerHTML='<div style="padding:18px 2px;color:var(--muted);font-size:11px">Замеров пока нет. Добавь первый фактический размер.</div>';return}root.innerHTML=S.measurements.slice().reverse().map((m,ri)=>{const i=S.measurements.length-1-ri,min=Number(m.target)+Number(m.low),max=Number(m.target)+Number(m.high),ok=Number(m.actual)>=min&&Number(m.actual)<=max;return `<div class="measure-row"><span class="dim">${esc(m.name||'Размер')}</span><span>${Number(m.actual).toFixed(3)}</span><span class="range">${min.toFixed(3)}…${max.toFixed(3)}</span><span class="measure-status ${ok?'ok':'bad'}">${ok?'OK':'OUT'}</span><button class="measure-delete" data-mdel="${i}" title="Удалить">×</button></div>`}).join('');$$('[data-mdel]',root).forEach(b=>b.onclick=()=>{S.measurements.splice(+b.dataset.mdel,1);save();renderMeasurements()})}
function renderRouteSummary(){const r=$('#routeSummary');if(!r)return;const max=Math.max(0,...S.ops.map(o=>Number(o.rpm)||0)),warn=S.ops.filter(o=>(Number(o.rpm)||0)>MACHINE.maxRpm).length,tools=new Set(S.ops.map(o=>o.tool).filter(Boolean)).size;r.innerHTML=`<div class="route-stat"><small>Операций</small><b>${S.ops.length}</b></div><div class="route-stat"><small>Инструментов</small><b>${tools}</b></div><div class="route-stat"><small>Макс. S</small><b>${max||'—'} rpm</b></div><div class="route-stat"><small>Проверка</small><b style="color:${warn?'var(--amber)':'var(--green)'}">${warn?warn+' превыш.':'OK'}</b></div>`}
function renderOps(){const l=$('#operationsList'),e=$('#operationsEmpty');$('#techJobName').textContent=S.job?.name||'Без выбранной детали';$('#operationCount').textContent=S.ops.length+' оп.';l.innerHTML='';e.style.display=S.ops.length?'none':'grid';S.ops.forEach((o,i)=>{const over=(Number(o.rpm)||0)>MACHINE.maxRpm,r=document.createElement('div');r.className='operation-row';r.innerHTML=`<span class="op-index">${String(i+1).padStart(2,'0')}</span><div class="op-main"><b>${esc(o.type)}</b><small>${esc(o.tool||'Инструмент не задан')}${o.note?' · '+esc(o.note):''}</small>${over?`<span class="op-warning">⚠ S выше лимита ${MACHINE.maxRpm} rpm</span>`:''}</div><div class="op-values"><span>S<b>${esc(o.rpm||'—')}</b></span><span>F<b>${esc(o.feed||'—')}</b></span><span>ap<b>${esc(o.depth||'—')}</b></span></div><div class="op-tools"><button data-up="${i}" title="Выше">↑</button><button data-down="${i}" title="Ниже">↓</button><button data-edit="${i}" title="Редактировать">✎</button><button data-del="${i}" title="Удалить">×</button></div>`;l.append(r)});$$('[data-del]',l).forEach(b=>b.onclick=()=>{S.ops.splice(+b.dataset.del,1);save();renderOps();renderHome();toast('Операция удалена')});$$('[data-edit]',l).forEach(b=>b.onclick=()=>openOperation(+b.dataset.edit));$$('[data-up]',l).forEach(b=>b.onclick=()=>moveOp(+b.dataset.up,-1));$$('[data-down]',l).forEach(b=>b.onclick=()=>moveOp(+b.dataset.down,1));renderRouteSummary()}
function moveOp(i,d){const n=i+d;if(n<0||n>=S.ops.length)return;[S.ops[i],S.ops[n]]=[S.ops[n],S.ops[i]];save();renderOps()}
function renderTurret(){const root=$('#turretGrid');if(!root)return;root.innerHTML=S.turret.map((t,i)=>`<button class="turret-slot ${t?'':'empty'}" data-slot="${i}"><span class="slot-no">T${String(i+1).padStart(2,'0')}</span>${t?`<strong>${esc(t.name||t.type)}</strong><small>${esc(t.insert||t.type)}</small><span class="stick">${t.stick?`Вылет ${esc(t.stick)} мм`:esc(t.note||'Настроено')}</span>`:'<strong>Свободно</strong><small>Нажми, чтобы назначить инструмент</small>'}</button>`).join('');$$('[data-slot]',root).forEach(b=>b.onclick=()=>openTool(+b.dataset.slot));renderToolDatalist()}
function renderToolDatalist(){const d=$('#turretTools');if(!d)return;d.innerHTML=S.turret.map((t,i)=>t?`<option value="T${String(i+1).padStart(2,'0')} · ${esc(t.name||t.insert||t.type)}"></option>`:'').join('')}
function modal(id){const d=$(id);if(d&&!d.open)d.showModal()}
function calc(){const D=+$('#calcD').value,V=+$('#calcVc').value,f=+$('#calcF').value;if(!(D>0&&V>0&&f>=0))return;const n=1000*V/(Math.PI*D),vf=n*f;$('#calcRpm').textContent=Math.round(n).toLocaleString('ru-RU');$('#calcFeed').textContent=Math.round(vf).toLocaleString('ru-RU');const lim=$('#calcLimit');if(lim){const over=n>MACHINE.maxRpm;lim.className='limit-banner show '+(over?'warn':'ok');lim.textContent=over?`⚠ Расчёт даёт ${Math.round(n)} rpm, а профиль станка ограничен ${MACHINE.maxRpm} rpm. Ограничь S и пересчитай фактическую скорость резания.`:`✓ ${Math.round(n)} rpm находится в пределах профиля станка (${MACHINE.maxRpm} rpm).`}}
function info(k){const data={material304:['AISI 304','Стартовый ориентир для твердосплавного инструмента: точение 100–180 м/мин, расточка 80–150 м/мин, сверление пластинами 60–120 м/мин. Длинный вылет, слабая система и нестабильная СОЖ требуют более осторожного старта.'],threads:['Метрические резьбы','Ориентир под метчик: M8 → 6.8 мм, M10 → 8.5 мм, M12 → 10.2 мм, M16 → 14.0 мм, M16×1.5 → 14.5 мм. Для точного допуска сверяй конкретный стандарт и инструмент.'],inserts:['CNMG / WNMG','CNMG — ромб 80°, жёсткая двусторонняя пластина. WNMG — тригон 80°, шесть рабочих кромок. Реальные режимы зависят от сплава, стружколома, державки и материала.'],shopturn:['ShopTurn · 828D','Практический порядок: заготовка → ноль → инструмент → операция → геометрия/контур → режим → симуляция → безопасный первый запуск. Приложение не отправляет команды на станок.']}[k];if(!data)return;$('#infoTitle').textContent=data[0];$('#infoContent').innerHTML='<p>'+data[1]+'</p>';modal('#infoModal')}
function openOperation(i=-1){editingOp=i;const f=$('#operationForm');f.reset();const title=$('#operationModal h2');if(i>=0){const o=S.ops[i];title.textContent='Редактировать операцию';$('#opType').value=o.type;$('#opTool').value=o.tool||'';$('#opRpm').value=o.rpm||'';$('#opFeed').value=o.feed||'';$('#opDepth').value=o.depth||'';$('#opNote').value=o.note||''}else title.textContent='Добавить операцию';modal('#operationModal')}
function openTool(i){editingSlot=i;const t=S.turret[i]||{};$('#toolModalTitle').textContent='Позиция T'+String(i+1).padStart(2,'0');$('#toolType').value=t.type||'Наружный резец';$('#toolName').value=t.name||'';$('#toolInsert').value=t.insert||'';$('#toolStick').value=t.stick||'';$('#toolNote').value=t.note||'';modal('#toolModal')}
function exportProject(){const data={app:'CNC Assistant 828D',schemaVersion:2,exportedAt:new Date().toISOString(),machine:MACHINE,job:S.job,operations:S.ops,turret:S.turret,measurements:S.measurements,checks:S.checks};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a'),name=(S.job?.name||'cnc-project').replace(/[^a-zа-яё0-9_-]+/gi,'_');a.href=URL.createObjectURL(blob);a.download=name+'.cnc828.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Проект экспортирован')}
function importProject(file){const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d||(!d.job&&!d.operations))throw new Error('bad');S.job=d.job||null;S.ops=Array.isArray(d.operations)?d.operations:[];S.turret=Array.isArray(d.turret)?[...d.turret.slice(0,15),...Array(Math.max(0,15-d.turret.length)).fill(null)]:Array(15).fill(null);S.measurements=Array.isArray(d.measurements)?d.measurements:[];S.checks=d.checks&&typeof d.checks==='object'?d.checks:{};save();renderAll();toast('Проект импортирован')}catch{toast('Не удалось прочитать проект')}};r.readAsText(file)}
function events(){
  $$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#resumeJobBtn').onclick=()=>nav(S.job?'technology':'job');
  $$('[data-open]').forEach(b=>b.onclick=()=>b.dataset.open==='calculator'?modal('#calculatorModal'):b.dataset.open==='diagnostics'?modal('#diagnosticsModal'):info(b.dataset.open));
  $$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d)d.close()});
  $('#themeToggle').onclick=()=>{const x=document.documentElement.classList.toggle('light');localStorage.setItem(K.theme,x?'light':'dark');$('#themeToggle').textContent=x?'☀':'☾'};
  $('#jobForm').onsubmit=e=>{e.preventDefault();S.job={name:$('#jobName').value.trim(),material:$('#jobMaterial').value,stockDiameter:$('#stockDiameter').value,stockLength:$('#stockLength').value,qty:$('#jobQty').value,zero:$('#jobZero').value,controlDims:$('#controlDims').value.trim(),notes:$('#jobNotes').value.trim()};save();renderJob();renderHome();toast('Карточка сохранена')};
  $('#clearJobBtn').onclick=()=>{if(confirm('Очистить карточку детали, маршрут, замеры и checklist?')){S.job=null;S.ops=[];S.measurements=[];S.checks={};save();renderAll();toast('Рабочий проект очищен')}};
  $('#exportProjectBtn').onclick=exportProject;$('#importProjectBtn').onclick=()=>$('#importProjectFile').click();$('#importProjectFile').onchange=e=>{const f=e.target.files?.[0];if(f)importProject(f);e.target.value=''};
  $('#measureForm').onsubmit=e=>{e.preventDefault();const target=Number($('#mTarget').value),actual=Number($('#mActual').value),low=Number($('#mLow').value||0),high=Number($('#mHigh').value||0);if(!Number.isFinite(target)||!Number.isFinite(actual)){toast('Введи номинал и фактический размер');return}S.measurements.push({name:$('#mName').value.trim()||'Размер',target,actual,low,high,at:Date.now()});save();$('#mActual').value='';renderMeasurements();toast('Замер добавлен')};
  $('#clearMeasuresBtn').onclick=()=>{if(S.measurements.length&&confirm('Очистить журнал размеров?')){S.measurements=[];save();renderMeasurements()}};
  $('#cuttingForm').onsubmit=e=>{e.preventDefault();calc()};$$('#cuttingForm input').forEach(i=>i.oninput=calc);
  $$('#diagnosticChips button').forEach(b=>b.onclick=()=>{$$('#diagnosticChips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#diagResult').innerHTML='<strong>Порядок проверки</strong><ol>'+diag[b.dataset.diag].map(x=>'<li>'+x+'</li>').join('')+'</ol>'});
  $('#addOperationBtn').onclick=()=>openOperation();$('#emptyAddOperation').onclick=()=>openOperation();
  $('#operationForm').onsubmit=e=>{e.preventDefault();const op={type:$('#opType').value,tool:$('#opTool').value.trim(),rpm:$('#opRpm').value,feed:$('#opFeed').value,depth:$('#opDepth').value,note:$('#opNote').value.trim()};if(editingOp>=0)S.ops[editingOp]=op;else S.ops.push(op);save();$('#operationModal').close();renderOps();renderHome();toast(editingOp>=0?'Операция обновлена':'Операция добавлена');editingOp=-1};
  $('#toolForm').onsubmit=e=>{e.preventDefault();if(editingSlot<0)return;S.turret[editingSlot]={type:$('#toolType').value,name:$('#toolName').value.trim(),insert:$('#toolInsert').value.trim(),stick:$('#toolStick').value,note:$('#toolNote').value.trim()};save();$('#toolModal').close();renderTurret();toast('Позиция T'+String(editingSlot+1).padStart(2,'0')+' сохранена')};
  $('#removeToolBtn').onclick=()=>{if(editingSlot<0)return;S.turret[editingSlot]=null;save();$('#toolModal').close();renderTurret();toast('Позиция освобождена')};
  $('#clearTurretBtn').onclick=()=>{if(confirm('Очистить все 15 позиций револьвера?')){S.turret=Array(15).fill(null);save();renderTurret()}};
  $('#referenceSearch').oninput=e=>{const q=e.target.value.toLowerCase().trim();$$('.reference-card').forEach(c=>c.style.display=!q||c.dataset.search.includes(q)||c.textContent.toLowerCase().includes(q)?'block':'none')};
}
function net(){const on=navigator.onLine;$('#networkStatus').classList.toggle('online',on);$('#networkStatus span').textContent=on?'Онлайн · PWA готов':'Оффлайн · PWA готов'}
function renderAll(){renderJob();renderSetup();renderMeasurements();renderOps();renderTurret();renderHome();calc()}
function init(){load();injectUI();events();renderAll();net();$('#themeToggle').textContent=document.documentElement.classList.contains('light')?'☀':'☾';addEventListener('online',net);addEventListener('offline',net);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
document.addEventListener('DOMContentLoaded',init);
