const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const K={job:'cnc828.job.v1',ops:'cnc828.ops.v1',theme:'cnc828.theme.v1'};const S={job:null,ops:[]};
const diag={squeal:['Уменьши обороты на 10–15% и проверь, меняется ли тон.','Проверь вылет и жёсткость державки.','Не занижай подачу до трения: пластина должна резать.','Проверь износ и геометрию пластины.','Для нержавейки обеспечь стабильную СОЖ.'],vibration:['Проверь вылет инструмента и детали.','Снизь обороты на 15–25% и повтори проход.','Проверь крепление державки, пластины и заготовки.','Измени глубину резания, если работа идёт на границе радиуса вершины.'],chips:['Сверь подачу с диапазоном стружколома.','Если стружка длинная и всё стабильно — повышай подачу небольшими шагами.','Проверь глубину резания и направление СОЖ.'],size:['Проверь повторяемость измерения и температуру детали.','Проверь износ кромки и налипание.','Зафиксируй тренд по нескольким деталям перед коррекцией.','На чистовой держи постоянный припуск.']};
function load(){try{S.job=JSON.parse(localStorage.getItem(K.job)||'null')}catch{}try{S.ops=JSON.parse(localStorage.getItem(K.ops)||'[]')}catch{}if(localStorage.getItem(K.theme)==='light')document.documentElement.classList.add('light')}
function save(){S.job?localStorage.setItem(K.job,JSON.stringify(S.job)):localStorage.removeItem(K.job);localStorage.setItem(K.ops,JSON.stringify(S.ops))}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function nav(v){$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));if(v==='job')renderJob();if(v==='technology')renderOps();scrollTo({top:0,behavior:'smooth'})}
function renderHome(){const b=$('#jobProgress .progress-track span'),m=$('#jobProgress .progress-meta');if(!S.job){$('#currentJobTitle').textContent='Деталь не выбрана';b.style.width='0%';m.innerHTML='<span>Создай карточку детали</span><b>0%</b>';return}$('#currentJobTitle').textContent=S.job.name||'Без названия';const p=[S.job.name,S.job.material,S.job.stockDiameter,S.job.controlDims,S.ops.length].filter(Boolean).length*20;b.style.width=p+'%';m.innerHTML=`<span>${S.job.material} · Ø${S.job.stockDiameter||'—'} · ${S.ops.length} оп.</span><b>${p}%</b>`}
function renderJob(){const j=S.job||{};['Name','Material','Qty','Zero','Notes'].forEach(()=>{});$('#jobName').value=j.name||'';$('#jobMaterial').value=j.material||'AISI 304';$('#stockDiameter').value=j.stockDiameter||'';$('#stockLength').value=j.stockLength||'';$('#jobQty').value=j.qty||1;$('#jobZero').value=j.zero||'G54 · торец детали';$('#controlDims').value=j.controlDims||'';$('#jobNotes').value=j.notes||'';$('#jobContextName').textContent=j.name||'Новая деталь';const d=$$('#jobContextList dd');d[0].textContent=j.material||'—';d[1].textContent=j.stockDiameter?`Ø${j.stockDiameter} × ${j.stockLength||'—'} мм`:'—';d[2].textContent=j.qty?j.qty+' шт.':'—';d[3].textContent=j.zero||'—'}
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function renderOps(){const l=$('#operationsList'),e=$('#operationsEmpty');$('#techJobName').textContent=S.job?.name||'Без выбранной детали';$('#operationCount').textContent=S.ops.length+' оп.';l.innerHTML='';e.style.display=S.ops.length?'none':'grid';S.ops.forEach((o,i)=>{const r=document.createElement('div');r.className='operation-row';r.innerHTML=`<span class="op-index">${String(i+1).padStart(2,'0')}</span><div class="op-main"><b>${esc(o.type)}</b><small>${esc(o.tool||'Инструмент не задан')}${o.note?' · '+esc(o.note):''}</small></div><div class="op-values"><span>S<b>${o.rpm||'—'}</b></span><span>F<b>${o.feed||'—'}</b></span><span>ap<b>${o.depth||'—'}</b></span></div><button class="op-delete" data-del="${i}">×</button>`;l.append(r)});$$('[data-del]',l).forEach(b=>b.onclick=()=>{S.ops.splice(+b.dataset.del,1);save();renderOps();renderHome();toast('Операция удалена')})}
function modal(id){const d=$(id);if(d&&!d.open)d.showModal()}
function calc(){const D=+$('#calcD').value,V=+$('#calcVc').value,f=+$('#calcF').value;if(!(D>0&&V>0&&f>=0))return;const n=1000*V/(Math.PI*D);$('#calcRpm').textContent=Math.round(n).toLocaleString('ru-RU');$('#calcFeed').textContent=Math.round(n*f).toLocaleString('ru-RU')}
function info(k){const data={material304:['AISI 304','Точение т/с пластиной: Vc примерно 100–180 м/мин. Расточка: 80–150 м/мин. Сверление пластинами: 60–120 м/мин. При длинном вылете начинай ниже.'],threads:['Метрические резьбы','Ориентир под метчик: M8 → 6.8 мм, M10 → 8.5 мм, M12 → 10.2 мм, M16 → 14.0 мм, M16×1.5 → 14.5 мм. Проверяй допуск по таблице производителя.'],inserts:['CNMG / WNMG','CNMG — ромб 80°, жёсткая двусторонняя пластина. WNMG — тригон 80°, шесть рабочих кромок. Конкретные режимы зависят от сплава и стружколома.'],shopturn:['ShopTurn · 828D','Логика: заготовка → ноль → инструмент → операция → контур/размер → режим → проверка. Приложение не отправляет команды на станок и не заменяет безопасный первый запуск.']}[k];if(!data)return;$('#infoTitle').textContent=data[0];$('#infoContent').innerHTML='<p>'+data[1]+'</p>';modal('#infoModal')}
function events(){$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#resumeJobBtn').onclick=()=>nav(S.job?'technology':'job');$$('[data-open]').forEach(b=>b.onclick=()=>b.dataset.open==='calculator'?modal('#calculatorModal'):b.dataset.open==='diagnostics'?modal('#diagnosticsModal'):info(b.dataset.open));$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.onclick=e=>{if(e.target===d)d.close()});$('#themeToggle').onclick=()=>{const x=document.documentElement.classList.toggle('light');localStorage.setItem(K.theme,x?'light':'dark');$('#themeToggle').textContent=x?'☀':'☾'};$('#jobForm').onsubmit=e=>{e.preventDefault();S.job={name:$('#jobName').value.trim(),material:$('#jobMaterial').value,stockDiameter:$('#stockDiameter').value,stockLength:$('#stockLength').value,qty:$('#jobQty').value,zero:$('#jobZero').value,controlDims:$('#controlDims').value.trim(),notes:$('#jobNotes').value.trim()};save();renderJob();renderHome();toast('Карточка сохранена')};$('#clearJobBtn').onclick=()=>{if(confirm('Очистить карточку детали и маршрут?')){S.job=null;S.ops=[];save();renderJob();renderOps();renderHome();toast('Очищено')}};$('#cuttingForm').onsubmit=e=>{e.preventDefault();calc()};$$('#cuttingForm input').forEach(i=>i.oninput=calc);$$('#diagnosticChips button').forEach(b=>b.onclick=()=>{$$('#diagnosticChips button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#diagResult').innerHTML='<strong>Порядок проверки</strong><ol>'+diag[b.dataset.diag].map(x=>'<li>'+x+'</li>').join('')+'</ol>'});const add=()=>modal('#operationModal');$('#addOperationBtn').onclick=add;$('#emptyAddOperation').onclick=add;$('#operationForm').onsubmit=e=>{e.preventDefault();S.ops.push({type:$('#opType').value,tool:$('#opTool').value.trim(),rpm:$('#opRpm').value,feed:$('#opFeed').value,depth:$('#opDepth').value,note:$('#opNote').value.trim()});save();e.target.reset();$('#operationModal').close();renderOps();renderHome();toast('Операция добавлена')};$('#referenceSearch').oninput=e=>{const q=e.target.value.toLowerCase().trim();$$('.reference-card').forEach(c=>c.style.display=!q||c.dataset.search.includes(q)||c.textContent.toLowerCase().includes(q)?'block':'none')}}
function net(){const on=navigator.onLine;$('#networkStatus').classList.toggle('online',on);$('#networkStatus span').textContent=on?'Онлайн · PWA готов':'Оффлайн · PWA готов'}
function init(){load();events();renderJob();renderOps();renderHome();calc();net();$('#themeToggle').textContent=document.documentElement.classList.contains('light')?'☀':'☾';addEventListener('online',net);addEventListener('offline',net);if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}document.addEventListener('DOMContentLoaded',init);
